# Generated by Django 5.2.1 on 2025-06-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='expires',
        ),
    ]
