# Generated by Django 5.2.1 on 2025-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('SSH', 'Ssh'), ('K8S', 'K8S')], max_length=255),
        ),
    ]
