# Generated by Django 5.2.1 on 2025-07-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_alter_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
