# Generated by Django 5.2.1 on 2025-07-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_log_input_tokens_log_output_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.PositiveIntegerField(default=8000),
        ),
    ]
