name: Build and deploy

on:
  push:
    branches: [ 'main' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Registry
        run: docker login ${{ secrets.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image
        run: |
          export TAG=${GITHUB_SHA::8}
          docker build . -t ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG}
          docker push ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG}

  deploy:
    runs-on: ubuntu-latest
    container: curlimages/curl:latest
    needs: build-and-push-image
    steps:
      - name: Deploy on Kubit
        run: |
          export TAG=${GITHUB_SHA::8}
          curl -X POST \
          -F DOCKER_TAG=${TAG} \
          -H "Authorization: Bearer ${{ secrets.KUBIT_WEBHOOK_TOKEN }}" \
          "${{ secrets.KUBIT_WEBHOOK_URL }}"